#Expyriment 1.0.0 (Python 3.11.6), .xpe-file, coding: UTF-8
#date: Thu Oct 16 2025 15:38:53
#sha1: 8d316d
#modules: constants.py (bf38d4), meg.py (23cfe5), eyelink.py (74605b)
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Darwin', node='Barbus-MacBook-Air.local', release='24.6.0', version='Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:51 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T8112', machine='arm64')
Time,Type,Event,Value,Detail,Detail2
571,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/louve.png
576,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/poule.png
580,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/tasse.png
584,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/malle.png
589,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/carre.png
594,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/cercle.png
599,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/etoile.png
602,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/croix.png
606,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/pentagone.png
610,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/losange.png
634,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/instr_1.png
662,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/instr_2.png
692,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/instr_3.png
721,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/instr_4.png
745,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/instr_5.png
771,Picture,loaded,/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Stimuli/instr_6.png
2293,design,log,
#design: #exp: Pushmi
#design: #dvn: subject_id,trial_type,block_number,trial_number,assignment_order,shape_pair,shape1,label1,shape2,label2,agent,patient,agent_shape,patient_shape,central_shape,lateral_position,movement,outcome,ground_truth,change,test_sentence,correct_key,timestamp,response,rt,correct
#design: block_cnt,block_id,trial_cnt,trial_id
2293,design,logged,
2293,Experiment,started
2296,Stimulus,presented,44
2827,Keyboard,received,32,wait
2827,Stimulus,presented,0
2829,Stimulus,presented,35
2879,Stimulus,presented,35
3327,stderr,received,'--- Logging error ---'
3328,stderr,received,'Traceback (most recent call last):'
3329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
3329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
3329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
3329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
3329,stderr,received,'TypeError: not all arguments converted during string formatting'
3329,stderr,received,'Call stack:'
3329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
3329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 210, in run_main_trial\n    draw_seq(assignment_seq(order, shape1, label1, shape2, label2))'
3329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 109, in draw_seq\n    draw(duration=dur, event=evt)'
3329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
3329,stderr,received,"Message: 'fix_init duration: '\nArguments: (500,)"
3329,Stimulus,presented,21
3329,Stimulus,presented,0
3346,Stimulus,presented,35
3379,Stimulus,presented,21
3396,Stimulus,presented,35
4329,stderr,received,'--- Logging error ---'
4329,stderr,received,'Traceback (most recent call last):'
4329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
4329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
4329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
4329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
4329,stderr,received,'TypeError: not all arguments converted during string formatting'
4329,stderr,received,'Call stack:'
4329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
4329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 210, in run_main_trial\n    draw_seq(assignment_seq(order, shape1, label1, shape2, label2))'
4329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 113, in draw_seq\n    draw(stims, duration=dur, event=evt)'
4329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
4329,stderr,received,"Message: 'assign_1_label duration: '\nArguments: (1000,)"
4329,Stimulus,presented,8
4329,Stimulus,presented,0
4346,Stimulus,presented,35
4379,Stimulus,presented,8
4396,Stimulus,presented,35
5329,stderr,received,'--- Logging error ---'
5329,stderr,received,'Traceback (most recent call last):'
5329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
5329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
5329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
5329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
5329,stderr,received,'TypeError: not all arguments converted during string formatting'
5329,stderr,received,'Call stack:'
5329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
5329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 210, in run_main_trial\n    draw_seq(assignment_seq(order, shape1, label1, shape2, label2))'
5329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 113, in draw_seq\n    draw(stims, duration=dur, event=evt)'
5329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
5329,stderr,received,"Message: 'assign_1_shape duration: '\nArguments: (1000,)"
5329,Stimulus,presented,0
5346,Stimulus,presented,35
5396,Stimulus,presented,35
6329,stderr,received,'--- Logging error ---'
6329,stderr,received,'Traceback (most recent call last):'
6329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
6329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
6329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
6329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
6329,stderr,received,'TypeError: not all arguments converted during string formatting'
6329,stderr,received,'Call stack:'
6329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
6329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 210, in run_main_trial\n    draw_seq(assignment_seq(order, shape1, label1, shape2, label2))'
6329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 109, in draw_seq\n    draw(duration=dur, event=evt)'
6329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
6329,stderr,received,"Message: 'fix_inter_assign duration: '\nArguments: (1000,)"
6329,Stimulus,presented,23
6329,Stimulus,presented,0
6345,Stimulus,presented,35
6379,Stimulus,presented,23
6396,Stimulus,presented,35
7329,stderr,received,'--- Logging error ---'
7329,stderr,received,'Traceback (most recent call last):'
7329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
7329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
7329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
7329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
7329,stderr,received,'TypeError: not all arguments converted during string formatting'
7329,stderr,received,'Call stack:'
7329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
7329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 210, in run_main_trial\n    draw_seq(assignment_seq(order, shape1, label1, shape2, label2))'
7329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 113, in draw_seq\n    draw(stims, duration=dur, event=evt)'
7329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
7329,stderr,received,"Message: 'assign_2_label duration: '\nArguments: (1000,)"
7329,Stimulus,presented,5
7329,Stimulus,presented,0
7346,Stimulus,presented,35
7379,Stimulus,presented,5
7396,Stimulus,presented,35
8329,stderr,received,'--- Logging error ---'
8329,stderr,received,'Traceback (most recent call last):'
8329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
8329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
8329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
8329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
8329,stderr,received,'TypeError: not all arguments converted during string formatting'
8329,stderr,received,'Call stack:'
8329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
8329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 210, in run_main_trial\n    draw_seq(assignment_seq(order, shape1, label1, shape2, label2))'
8329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 113, in draw_seq\n    draw(stims, duration=dur, event=evt)'
8329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
8329,stderr,received,"Message: 'assign_2_shape duration: '\nArguments: (1000,)"
8329,Stimulus,presented,0
8346,Stimulus,presented,35
8396,Stimulus,presented,35
9329,stderr,received,'--- Logging error ---'
9329,stderr,received,'Traceback (most recent call last):'
9329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
9329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
9329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
9329,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
9329,stderr,received,'TypeError: not all arguments converted during string formatting'
9329,stderr,received,'Call stack:'
9329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
9329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 210, in run_main_trial\n    draw_seq(assignment_seq(order, shape1, label1, shape2, label2))'
9329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 109, in draw_seq\n    draw(duration=dur, event=evt)'
9329,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
9329,stderr,received,"Message: 'fix_post_assign duration: '\nArguments: (1000,)"
9329,Stimulus,presented,8
9329,Stimulus,presented,0
9345,Stimulus,presented,35
9379,Stimulus,presented,8
9395,Stimulus,presented,35
10329,stderr,received,'--- Logging error ---'
10330,stderr,received,'Traceback (most recent call last):'
10330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
10330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
10330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
10330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
10330,stderr,received,'TypeError: not all arguments converted during string formatting'
10330,stderr,received,'Call stack:'
10330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
10330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 216, in run_main_trial\n    draw_seq(['
10330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 113, in draw_seq\n    draw(stims, duration=dur, event=evt)'
10330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
10330,stderr,received,"Message: 'central_flash duration: '\nArguments: (1000,)"
10330,Stimulus,presented,0
10346,Stimulus,presented,35
10396,Stimulus,presented,35
11130,stderr,received,'--- Logging error ---'
11130,stderr,received,'Traceback (most recent call last):'
11130,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
11130,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
11130,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
11130,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
11130,stderr,received,'TypeError: not all arguments converted during string formatting'
11130,stderr,received,'Call stack:'
11130,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
11130,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 216, in run_main_trial\n    draw_seq(['
11130,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 109, in draw_seq\n    draw(duration=dur, event=evt)'
11130,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
11130,stderr,received,"Message: 'fix_inter_flash duration: '\nArguments: (800,)"
11130,Stimulus,presented,5
11130,Stimulus,presented,0
11145,Stimulus,presented,35
11181,Stimulus,presented,5
11195,Stimulus,presented,35
11330,stderr,received,'--- Logging error ---'
11330,stderr,received,'Traceback (most recent call last):'
11330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
11330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
11330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
11330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
11330,stderr,received,'TypeError: not all arguments converted during string formatting'
11330,stderr,received,'Call stack:'
11330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
11330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 216, in run_main_trial\n    draw_seq(['
11330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 113, in draw_seq\n    draw(stims, duration=dur, event=evt)'
11330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
11330,stderr,received,"Message: 'lateral_flash duration: '\nArguments: (200,)"
11330,Stimulus,presented,0
11346,Stimulus,presented,35
11396,Stimulus,presented,35
12130,stderr,received,'--- Logging error ---'
12130,stderr,received,'Traceback (most recent call last):'
12130,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
12130,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
12130,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
12130,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
12130,stderr,received,'TypeError: not all arguments converted during string formatting'
12130,stderr,received,'Call stack:'
12130,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
12130,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 216, in run_main_trial\n    draw_seq(['
12130,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 109, in draw_seq\n    draw(duration=dur, event=evt)'
12130,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
12130,stderr,received,"Message: 'fix_post_flash duration: '\nArguments: (800,)"
12131,Stimulus,presented,8
12131,Stimulus,presented,5
12131,Stimulus,presented,0
12146,Stimulus,presented,35
12180,Stimulus,presented,8
12180,Stimulus,presented,5
12196,Stimulus,presented,35
12330,stderr,received,'--- Logging error ---'
12330,stderr,received,'Traceback (most recent call last):'
12330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
12330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
12330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
12330,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
12330,stderr,received,'TypeError: not all arguments converted during string formatting'
12330,stderr,received,'Call stack:'
12330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
12330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 237, in run_main_trial\n    draw_seq(['
12330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 111, in draw_seq\n    draw(*stims, duration=dur, event=evt)'
12330,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
12330,stderr,received,"Message: 'outcome duration: '\nArguments: (200,)"
12330,Stimulus,presented,0
12346,Stimulus,presented,35
12396,Stimulus,presented,35
12830,stderr,received,'--- Logging error ---'
12830,stderr,received,'Traceback (most recent call last):'
12830,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
12830,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
12830,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
12830,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
12830,stderr,received,'TypeError: not all arguments converted during string formatting'
12830,stderr,received,'Call stack:'
12830,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
12830,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 237, in run_main_trial\n    draw_seq(['
12830,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 109, in draw_seq\n    draw(duration=dur, event=evt)'
12830,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
12830,stderr,received,"Message: 'fix_post_outcome duration: '\nArguments: (500,)"
12830,Stimulus,presented,25
12830,Stimulus,presented,0
12846,Stimulus,presented,35
12880,Stimulus,presented,25
12896,Stimulus,presented,35
13230,stderr,received,'--- Logging error ---'
13230,stderr,received,'Traceback (most recent call last):'
13230,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
13230,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
13230,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
13230,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
13230,stderr,received,'TypeError: not all arguments converted during string formatting'
13230,stderr,received,'Call stack:'
13230,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
13230,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 244, in run_main_trial\n    draw(words[w], duration=WORD_T, event=f\'test_{i}\')'
13230,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
13230,stderr,received,"Message: 'test_1 duration: '\nArguments: (400,)"
13230,Stimulus,presented,21
13231,Stimulus,presented,0
13246,Stimulus,presented,35
13280,Stimulus,presented,21
13296,Stimulus,presented,35
13630,stderr,received,'--- Logging error ---'
13630,stderr,received,'Traceback (most recent call last):'
13630,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^'
13630,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^'
13630,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 687, in format\n    record.message = record.getMessage()\n                     ^^^^^^^^^^^^^^^^^^^'
13630,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/logging/__init__.py", line 377, in getMessage\n    msg = msg % self.args\n          ~~~~^~~~~~~~~~~'
13630,stderr,received,'TypeError: not all arguments converted during string formatting'
13630,stderr,received,'Call stack:'
13630,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>\n    run_main_trial(**params)'
13630,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 244, in run_main_trial\n    draw(words[w], duration=WORD_T, event=f\'test_{i}\')'
13630,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 103, in draw\n    logger.info(f"{event} duration: ", exp.clock.time - t0)'
13630,stderr,received,"Message: 'test_2 duration: '\nArguments: (400,)"
13630,Stimulus,presented,29
13630,Stimulus,presented,0
13646,Stimulus,presented,35
13670,Experiment,ended
13798,stderr,received,'Traceback (most recent call last):'
13798,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 363, in <module>'
13798,stderr,received,'    run_main_trial(**params)'
13798,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 244, in run_main_trial'
13798,stderr,received,"    draw(words[w], duration=WORD_T, event=f'test_{i}')"
13798,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 101, in draw'
13799,stderr,received,'    present(*stims, pulse, duration=50, event=event)'
13799,stderr,received,'  File "/Users/Barbu/Documents/Postdoc/Experiments/Pushmi/MEG/Scripts/experiment.py", line 90, in present'
13799,stderr,received,'    exp.clock.wait(remaining)'
13799,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/expyriment/misc/_clock.py", line 157, in wait'
13799,stderr,received,'    while (get_time() < start + waiting_time / 1000):'
13799,stderr,received,'           ^^^^^^^^^^'
13799,stderr,received,'  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/expyriment/misc/_timer.py", line 21, in get_time'
13799,stderr,received,'    return perf_counter()'
13799,stderr,received,'           ^^^^^^^^^^^^^^'
13799,stderr,received,'KeyboardInterrupt'
